services:
  - type: web
    name: n8n
    env: node
    region: oregon
    plan: free
    runtime: node
    buildCommand: "npm install"
    startCommand: "n8n start"
    envVars:
      - key: N8N_HOST
        value: n8n-hrew.onrender.com
      - key: N8N_PORT
        value: 8080
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-hrew.onrender.com
      - key: NODE_ENV
        value: production
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: N8N_ENCRYPTION_KEY
        value: mysecretenckey1234567890abcdef

databases:
  - name: n8n-db
    plan: free
